src/objects/Car__c.object
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ChampionshipPoints__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <label>Championship Points</label>
</CustomObject>

runtime/samples/forcedotcom-enterprise-architecture/src/objects/Contestant__c.object
<CustomObject>
    <fields>
        <fullName>Car__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Car</label>
        <referenceTo>Car__c</referenceTo>
        <relationshipLabel>Contestants</relationshipLabel>
        <relationshipName>Contestants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ChampionshipPoints__c</fullName>
        <label>Championship Points</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DNF__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DNF</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DriverRace__c</fullName>
        <formula>Driver__r.Name + &apos; (&apos; + Race__r.Name + &apos;)&apos;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Driver and Race</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Driver__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Driver</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only Active Drivers can be contestants in a race.</errorMessage>
            <filterItems>
                <field>Driver__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>Only Drivers who&apos;s status is active are permitted.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Driver__c</referenceTo>
        <relationshipLabel>Contestants</relationshipLabel>
        <relationshipName>Contestants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GridPosition__c</fullName>
        <label>Grid Position</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Qualification1LapTime__c</fullName>
        <label>Qualification 1 Lap Time</label>
        <precision>9</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Qualification2LapTime__c</fullName>
        <label>Qualification 2 Lap Time</label>
        <precision>9</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Qualification3LapTime__c</fullName>
        <label>Qualification 3 Lap Time</label>
        <precision>9</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RacePosition__c</fullName>
        <label>Race Position</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RaceTime__c</fullName>
        <label>Race Time</label>
        <precision>9</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <label>Race</label>
        <referenceTo>Race__c</referenceTo>
        <relationshipLabel>Contestants</relationshipLabel>
        <relationshipName>Contestants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RetirementReason__c</fullName>
        <label>Retirement Reason</label>
        <type>TextArea</type>
    </fields>
    <label>Contestant</label>
    <nameField>
        <displayFormat>CONTESTANT-{00000000}</displayFormat>
        <label>Contestant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contestants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

samples/forcedotcom-enterprise-architecture/src/objects/Driver__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Drivers</relationshipLabel>
        <relationshipName>Drivers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Driver</label>
    <nameField>
        <label>Driver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Race__c.object
<CustomObject>
    <fields>
        <fullName>Season__c</fullName>
        <label>Season</label>
        <referenceTo>Season__c</referenceTo>
        <relationshipLabel>Races</relationshipLabel>
        <relationshipName>Races</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

samples/forcedotcom-enterprise-architecture/src/objects/Season__c.object
<CustomObject>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

samples/forcedotcom-enterprise-architecture/src/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

samples/forcedotcom-enterprise-architecture/src/classes/ContestantsSelector.cls
public virtual class ContestantsSelector extends fflib_SObjectSelector
{
	public static ContestantsSelector newInstance() 
	{ 
		return (ContestantsSelector) Application.Selector.newInstance(Contestant__c.SObjectType); 
	}

	public List<Schema.SObjectField> getSObjectFieldList()
	{
		return new List<Schema.SObjectField> {
			Contestant__c.Id,
			Contestant__c.Name,
			Contestant__c.ChampionshipPoints__c,
			Contestant__c.DNF__c,
			Contestant__c.Driver__c,
			Contestant__c.DriverRace__c,
			Contestant__c.GridPosition__c,
			Contestant__c.Qualification1LapTime__c,
			Contestant__c.Qualification2LapTime__c,
			Contestant__c.Qualification3LapTime__c,
			Contestant__c.Race__c,
			Contestant__c.RacePosition__c,
			Contestant__c.RaceTime__c,
			Contestant__c.RetirementReason__c
		};
	}

	public Schema.SObjectType getSObjectType()
	{
		return Contestant__c.sObjectType;
	}

	public override String getOrderBy()
	{
		return 'Race__r.Season__r.Name, Race__r.Name, RacePosition__c';
	}

	public List<Contestant__c> selectById(Set<Id> ids)
	{
		return (List<Contestant__c>) super.selectSObjectsById(ids);
	}

	public List<Contestant__c> selectByIdWithDriver(Set<Id> driverIds)
	{
		assertIsAccessible();

		DriversSelector driversSelector = new DriversSelector();
		driversSelector.assertIsAccessible();

		return Database.query(
			String.format('select {0},{1} from {2} where Id in :driverIds order by {3}', 
			new List<String>{
				getFieldListString(),
				driversSelector.getRelatedFieldListString('Driver__r'),
				getSObjectName(),
				getOrderBy()}));		
	}	

	public virtual Map<Id, List<Summary>> selectByRaceIdWithContestantSummary(Set<Id> raceIds)
	{
		assertIsAccessible();
		new DriversSelector().assertIsAccessible();
		new CarsSelector().assertIsAccessible();
		new TeamsSelector().assertIsAccessible();
		Map<Id, List<Summary>> summariesByRaceId = new Map<Id, List<Summary>>();		
		for(Contestant__c contestant : 
				Database.query(
					String.format(
						'select {0} from {1} where Race__c in :raceIds order by {2}', 
						new List<String>{
							String.join(
								new List<String> {
									'Race__r.Season__r.Name',
									'Race__r.Name',
									'RacePosition__c',
									'Driver__r.Name',
									'Driver__r.Team__r.Name',
									'Car__r.Name' }, ','),
							getSObjectName(),
							getOrderBy()})))
		{
			List<Summary> summaries = summariesByRaceId.get(contestant.Race__c);
			if(summaries==null)
				summariesByRaceId.put(contestant.Race__c, summaries = new List<Summary>());
			summaries.add(new Summary(contestant));
		}
		return summariesByRaceId;
	}

	public class Summary 
	{
		private Contestant__c contestant;				
		public String Season { 
			get { return contestant.Race__r.Season__r.Name; }}		
		public String Race { 
			get { return contestant.Race__r.Name; } }	
		public Decimal Position { 
			get { return contestant.RacePosition__c; } }				
		public String Driver { 
			get { return contestant.Driver__r.Name; } }		
		public String Team { 
			get { return contestant.Driver__r.Team__r.Name; } }		
		public String Car { 
			get { return contestant.Car__r.Name; } }		
		@TestVisible			
		private Summary(Contestant__c contestant) { 
			this.contestant = contestant; }
	}
}