src/objects/ChampionshipPoints__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>PointsAwarded__c</fullName>
        <label>Points Awarded</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Championship Points</label>
</CustomObject>

runtime/samples/forcedotcom-enterprise-architecture/src/objects/Contestant__c.object
<CustomObject>
    <fields>
        <fullName>ChampionshipPoints__c</fullName>
        <label>Championship Points</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Contestant</label>
    <nameField>
        <displayFormat>CONTESTANT-{00000000}</displayFormat>
        <label>Contestant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contestants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

runtime/samples/forcedotcom-enterprise-architecture/src/classes/ContestantServiceTest.cls
@isTest
private class ContestantServiceTest 
{	
	@isTest static void testAwardPoints() 
	{
		SeasonService.importSeasons(TestData.asJSON());
		insert new ChampionshipPoints__c(Name = '1', PointsAwarded__c = 25);			
		ContestantService.awardChampionshipPoints(
			new Map<Id, SObject>([select Id from Contestant__c]).keySet());
	}

	@isTest static void testTemporary()
	{
		try {
			ContestantService.retireFromRace(null);
			System.assert(false);
		} catch (Exception e) {
			System.assertEquals('Not implemented', e.getMessage());
		}
	}
}