runtime/samples/forcedotcom-enterprise-architecture/src/objects/Contestant__c.object
<CustomObject>
    <fields>
        <fullName>Race__c</fullName>
        <label>Race</label>
        <referenceTo>Race__c</referenceTo>
        <relationshipLabel>Contestants</relationshipLabel>
        <relationshipName>Contestants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contestant</label>
    <nameField>
        <displayFormat>CONTESTANT-{00000000}</displayFormat>
        <label>Contestant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contestants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Race__c.object
<CustomObject>
    <fields>
        <fullName>FastestLapBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fastest Lap By</label>
        <referenceTo>Driver__c</referenceTo>
        <relationshipLabel>Races</relationshipLabel>
        <relationshipName>FastestLaps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PollPositionLapTime__c</fullName>
        <label>Poll Position Lap Time</label>
        <summarizedField>Contestant__c.Qualification1LapTime__c</summarizedField>
        <summaryForeignKey>Contestant__c.Race__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Season__c</fullName>
        <label>Season</label>
        <referenceTo>Season__c</referenceTo>
        <relationshipLabel>Races</relationshipLabel>
        <relationshipName>Races</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Scheduled</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Red Flagged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finished</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TotalDNFs__c</fullName>
        <label>Total DNFs</label>
        <summaryFilterItems>
            <field>Contestant__c.DNF__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Contestant__c.Race__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <formula>Season__r.Year__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Year</label>
        <type>Text</type>
    </fields>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

samples/forcedotcom-enterprise-architecture/src/objects/Season__c.object
<CustomObject>
    <fields>
        <fullName>Year__c</fullName>
        <defaultValue>TEXT(YEAR(TODAY()))</defaultValue>
        <externalId>true</externalId>
        <label>Year</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RacesSelector.cls
public class RacesSelector extends fflib_SObjectSelector
{
	public RacesSelector()
	{
		super();
	}

	public RacesSelector(Boolean includeFieldSetFields)
	{
		super(includeFieldSetFields);
	}

    public override List<Schema.FieldSet> getSObjectFieldSetList()
    {
        return new List<Schema.FieldSet> { 
        	SObjectType.Race__c.FieldSets.SeasonOverview 
        };
    }

	public List<Schema.SObjectField> getSObjectFieldList()
	{
		return new List<Schema.SObjectField> {
			Race__c.Id,
			Race__c.Name,
			Race__c.Year__c,
			Race__c.Status__c,
			Race__c.Season__c,
			Race__c.FastestLapBy__c,
			Race__c.PollPositionLapTime__c,
			Race__c.TotalDNFs__c
		};
	}

	public Schema.SObjectType getSObjectType()
	{
		return Race__c.sObjectType;
	}

	public List<Race__c> selectById(Set<Id> raceIds)
	{
		return (List<Race__c>) selectSObjectsById(raceIds);
	}

	public List<Race__c> selectByIdWithContestants(Set<Id> raceIds)
	{
		assertIsAccessible();

		ContestantsSelector contestantSelector = new ContestantsSelector();
		contestantSelector.assertIsAccessible();

		return (List<Race__c>) Database.query(
			String.format(
					'select {0}, ' +
					  '(select {1} ' +
					     'from Contestants__r order by {2})' + 
					  'from {3} ' +
					  'where id in :raceIds ' + 
					  'order by {4}', 
				new List<String>{
					getFieldListString(),
					contestantSelector.getFieldListString(),
					contestantSelector.getOrderBy(),
					getSObjectName(),
					getOrderBy()
				}));		
	}
}