samples/forcedotcom-enterprise-architecture/src/objects/Driver__c.object
<CustomObject>
    <fields>
        <fullName>DriverId__c</fullName>
        <label>Driver Id</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>FIASuperLicense__c</fullName>
        <defaultValue>false</defaultValue>
        <label>FIA Super License</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Drivers</relationshipLabel>
        <relationshipName>Drivers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Driver</label>
    <nameField>
        <label>Driver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

samples/forcedotcom-enterprise-architecture/src/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

samples/forcedotcom-enterprise-architecture/src/classes/DriversSelector.cls
public class DriversSelector extends fflib_SObjectSelector
{
	public static DriversSelector newInstance() 
	{ 
		return (DriversSelector) Application.Selector.newInstance(Driver__c.SObjectType); 
	}
    
	public List<Schema.SObjectField> getSObjectFieldList()
	{
		return new List<Schema.SObjectField> {
			Driver__c.Id,
			Driver__c.Name,
			Driver__c.FIASuperLicense__c,
			Driver__c.Team__c,
            Driver__c.DriverId__c
		};
	}

	public Schema.SObjectType getSObjectType()
	{
		return Driver__c.sObjectType;
	}

	public List<Driver__c> selectById(Set<Id> ids)
	{
		return (List<Driver__c>) super.selectSObjectsById(ids);
	}

	public List<Driver__c> selectByTeam(Set<Id> teamIds)
	{
		assertIsAccessible();
		return Database.query(
			String.format('SELECT {0} FROM {1} WHERE Team__c in :teamIds ORDER BY {2}', 
			new List<String>{getFieldListString(),getSObjectName(),getOrderBy()}));
	}
}